[package]
name = "slint_test"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.12.1", default-features = false, features = [
    "compat-1-2",
    "backend-linuxkms-noseat",
    #  "renderer-skia",
    "renderer-software",
] }

[build-dependencies]
slint-build = "1.12.1"